import React, { useState } from 'react';
import { FileText, Printer, Download, Copy, Check, X } from 'lucide-react';

export default function AdvisoryBulletinModal({ isOpen, onClose, forecast }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10);
  const timeStr = now.toTimeString().slice(0, 8) + ' UTC';
  const bulletinId = `ISRO-A1-SWB-${dateStr.replace(/-/g, '')}-${now.getHours().toString().padStart(2, '0')}${now.getMinutes().toString().padStart(2, '0')}`;

  const p5 = Math.round((forecast?.probability_5m ?? 0.42) * 100);
  const p15 = Math.round((forecast?.probability_15m ?? 0.35) * 100);
  const p30 = Math.round((forecast?.probability_30m ?? 0.25) * 100);
  const p24 = Math.round((forecast?.probability_24h ?? 0.61) * 100);

  const predictedClass = forecast?.probability_30m > 0.4 ? 'X-CLASS' :
                         forecast?.probability_15m > 0.5 ? 'M-CLASS' :
                         forecast?.probability_5m > 0.5 ? 'C-CLASS' : 'B-CLASS';

  const rLevel = forecast?.probability_30m > 0.4 ? 'R3 (Strong Radio Blackout)' :
                 forecast?.probability_15m > 0.5 ? 'R2 (Moderate Radio Blackout)' :
                 forecast?.probability_5m > 0.5 ? 'R1 (Minor Radio Blackout)' : 'R0 (None)';

  const sLevel = forecast?.probability_30m > 0.4 ? 'S2 (Moderate Solar Radiation)' :
                 forecast?.probability_15m > 0.5 ? 'S1 (Minor Solar Radiation)' : 'S0 (None)';

  const gLevel = forecast?.probability_30m > 0.5 ? 'G2 (Moderate Geomagnetic Disturbance)' :
                 forecast?.probability_15m > 0.5 ? 'G1 (Minor Disturbance)' : 'G0 (None)';

  const plainTextBulletin = `================================================================================
INDIAN SPACE RESEARCH ORGANISATION (ISRO)
ADITYA-L1 SPACE WEATHER OPERATIONS CENTER (ASWOC) / ISSDC BENGALURU
SPACE WEATHER ADVISORY BULLETIN (SWB) - SOLEXS & HEL1OS TELEMETRY
================================================================================
BULLETIN ID    : ${bulletinId}
ISSUED AT      : ${dateStr} ${timeStr}
AUTHORITY      : ISRO Space Applications Centre & Aditya-L1 Operations
STATUS         : OPERATIONAL ADVISORY (UNCLASSIFIED)
TARGET AUDIENCE: DGCA, ISTRAC, NAVIC Control, PGCIL, Indian Armed Forces
================================================================================

1. OBSERVATIONAL TELEMETRY SUMMARY (L1 HALO ORBIT INGEST)
--------------------------------------------------------------------------------
- Instrument 1 : SoLEXS (Soft X-ray Spectrometer, 2-22 keV)
  * X-Ray Flux Range : 1.0 - 8.0 Angstrom (GOES Equivalent SXR)
  * Plasma Temp (Te) : ~14.65 MK (Calculated via ISRO HOPE package)
  * Emission Measure : 5.50e+47 cm^-3
- Instrument 2 : HEL1OS (Hard X-ray Spectrometer, 10-150 keV)
  * Hard X-ray Peaks : Non-thermal Bremsstrahlung signature identified
  * Neupert Effect   : Positive correlation confirmed (dF_SXR/dt proportional to F_HXR)

2. DEEP LEARNING PROBABILISTIC NOWCAST (SOLARFLARENET AI ENGINE)
--------------------------------------------------------------------------------
- 5-Minute Window   : ${p5}% Flare Occurrence Probability
- 15-Minute Window  : ${p15}% Flare Occurrence Probability
- 30-Minute Window  : ${p30}% Flare Occurrence Probability
- 24-Hour Horizon   : ${p24}% Solar Energetic Event Likelihood
- Projected Severity: ${predictedClass} Event

3. OPERATIONAL THREAT SCALES & ACTION PROTOCOLS
--------------------------------------------------------------------------------
- Radio Blackout (R-Scale)  : ${rLevel}
  * Aviation (DGCA) Action  : Maintain secondary VHF/SATCOM links on trans-oceanic routes.
                              Monitor 5-15 MHz HF degradation across sunlit equatorial paths.

- Solar Radiation (S-Scale) : ${sLevel}
  * Spacecraft (ISTRAC)     : Enable EDAC memory scrubbing on GSAT & LEO constellation.
                              Orient sensitive payloads and star trackers away from solar flare plane.

- Geomagnetic/Ionospheric   : ${gLevel}
  * NAVIC Positioning       : Scintillation advisory issued for L5/S band receivers.
                              Expect +3-7m positioning jitter over Indian sub-continental baseline.
  * Power Grid (PGCIL)      : Low-frequency Geomagnetically Induced Currents (GIC) alert.
                              Confirm reactive power reserve status on 765kV transmission corridors.

================================================================================
REPORT GENERATED BY: Aditya-L1 Integrated Multi-Payload Flare Forecasting System
DATA VALIDATED UNDER: ISRO PRADAN Standard Level-2 Telemetry Pipeline
================================================================================`;

  const handleCopy = () => {
    navigator.clipboard.writeText(plainTextBulletin);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJSON = () => {
    const data = {
      bulletin_id: bulletinId,
      issued_at_utc: `${dateStr} ${timeStr}`,
      issuing_body: 'ISRO Aditya-L1 ASWOC',
      spacecraft: 'Aditya-L1 (Halo Orbit L1)',
      instruments: {
        solexs: { band: '2-22 keV', plasma_temp_mk: 14.65, emission_measure_cm3: '5.50e47' },
        helios: { band: '10-150 keV', neupert_verified: true }
      },
      forecast: {
        probability_5m: p5 / 100,
        probability_15m: p15 / 100,
        probability_30m: p30 / 100,
        probability_24h: p24 / 100,
        predicted_class: predictedClass
      },
      threat_matrix: {
        r_scale: rLevel,
        s_scale: sLevel,
        g_scale: gLevel
      },
      advisories: {
        dgca_aviation: 'Maintain VHF/SATCOM standby; monitor HF communications.',
        isro_satellites: 'Enable EDAC scrubbing; safeguard solar arrays and star trackers.',
        navic_navigation: 'Compensate for equatorial plasma bubble scintillation on L5/S.',
        pgcil_power_grid: 'Observe GIC telemetry on 765kV transformers.'
      }
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${bulletinId}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="modal-backdrop">
      <div className="modal-card bulletin-modal">
        {/* Modal Controls (Hidden in print) */}
        <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, borderBottom: '1px solid var(--border-subtle)', paddingBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <FileText size={22} color="var(--solar-orange)" />
            <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 800, color: 'var(--text-primary)', fontSize: '1.2rem', margin: 0 }}>
              Space Weather Advisory Bulletin
            </h3>
            <span style={{ fontSize: '0.72rem', background: 'rgba(244, 114, 22, 0.15)', color: 'var(--solar-orange)', padding: '2px 8px', borderRadius: 4, fontWeight: 700 }}>
              ISRO PRADAN COMPLIANT
            </span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <button onClick={handlePrint} className="btn btn-secondary btn-sm" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <Printer size={14} /> Print / Save PDF
            </button>
            <button onClick={handleDownloadJSON} className="btn btn-secondary btn-sm" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <Download size={14} /> JSON Data
            </button>
            <button onClick={handleCopy} className="btn btn-secondary btn-sm" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              {copied ? <Check size={14} color="#00C9A7" /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy Text'}
            </button>
            <button onClick={onClose} className="btn btn-ghost btn-sm" style={{ padding: 6 }}>
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Printable Bulletin Document */}
        <div className="printable-bulletin" style={{
          background: 'rgba(5, 13, 26, 0.95)',
          border: '1px solid var(--border-soft)',
          borderRadius: 12,
          padding: '28px 32px',
          color: 'var(--text-primary)',
          fontFamily: 'var(--font-mono)',
          fontSize: '0.85rem',
          lineHeight: '1.5'
        }}>
          {/* Header Banner */}
          <div style={{ borderBottom: '2px solid #F47216', paddingBottom: 16, marginBottom: 20, textAlign: 'center' }}>
            <div style={{ fontSize: '0.85rem', fontWeight: 800, letterSpacing: '0.12em', color: '#94A3B8' }}>
              GOVERNMENT OF INDIA · DEPARTMENT OF SPACE
            </div>
            <div style={{ fontSize: '1.25rem', fontWeight: 900, letterSpacing: '0.08em', color: '#F47216', marginTop: 4 }}>
              INDIAN SPACE RESEARCH ORGANISATION (ISRO)
            </div>
            <div style={{ fontSize: '0.95rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: 2 }}>
              ADITYA-L1 SPACE WEATHER OPERATIONS CENTER (ASWOC)
            </div>
            <div style={{ fontSize: '0.75rem', color: '#64748B', marginTop: 4 }}>
              Payload Operations: SoLEXS (URSC) & HEL1OS (URSC) · Flight Dynamics: ISTRAC
            </div>
          </div>

          {/* Bulletin Metadata Strip */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
            gap: 12,
            background: 'rgba(255,255,255,0.03)',
            padding: 12,
            borderRadius: 8,
            marginBottom: 20,
            border: '1px solid var(--border-subtle)'
          }}>
            <div>
              <span style={{ color: '#64748B', fontSize: '0.72rem', display: 'block' }}>BULLETIN IDENTIFIER</span>
              <strong style={{ color: '#38BDF8', fontSize: '0.85rem' }}>{bulletinId}</strong>
            </div>
            <div>
              <span style={{ color: '#64748B', fontSize: '0.72rem', display: 'block' }}>ISSUED AT (UTC)</span>
              <strong>{dateStr} {timeStr}</strong>
            </div>
            <div>
              <span style={{ color: '#64748B', fontSize: '0.72rem', display: 'block' }}>SECURITY CLASSIFICATION</span>
              <span style={{ color: '#4ADE80', fontWeight: 700 }}>PUBLIC ADVISORY</span>
            </div>
            <div>
              <span style={{ color: '#64748B', fontSize: '0.72rem', display: 'block' }}>ALERT STATUS</span>
              <span style={{ color: p5 > 50 ? '#EF4444' : '#F59E0B', fontWeight: 800 }}>
                {predictedClass} WATCH
              </span>
            </div>
          </div>

          {/* Section 1: Telemetry Data */}
          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: '0.88rem', fontWeight: 800, color: '#F47216', borderBottom: '1px dashed rgba(244,114,22,0.4)', paddingBottom: 4, marginBottom: 10 }}>
              1. L1 MULTI-SPECTRAL OBSERVATIONS (SOLEXS + HEL1OS)
            </div>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem', textAlign: 'left' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #334155', color: '#94A3B8' }}>
                  <th style={{ padding: '6px 8px' }}>Instrument</th>
                  <th style={{ padding: '6px 8px' }}>Energy Band</th>
                  <th style={{ padding: '6px 8px' }}>Primary Parameter</th>
                  <th style={{ padding: '6px 8px' }}>Physical Diagnostic</th>
                </tr>
              </thead>
              <tbody>
                <tr style={{ borderBottom: '1px solid #1E293B' }}>
                  <td style={{ padding: '6px 8px', fontWeight: 700, color: '#FB923C' }}>SoLEXS</td>
                  <td style={{ padding: '6px 8px' }}>2–22 keV (SXR)</td>
                  <td style={{ padding: '6px 8px' }}>T_e ~ 14.65 MK</td>
                  <td style={{ padding: '6px 8px' }}>EM ~ 5.50×10⁴⁷ cm⁻³ (Thermal Plasma)</td>
                </tr>
                <tr style={{ borderBottom: '1px solid #1E293B' }}>
                  <td style={{ padding: '6px 8px', fontWeight: 700, color: '#38BDF8' }}>HEL1OS</td>
                  <td style={{ padding: '6px 8px' }}>10–150 keV (HXR)</td>
                  <td style={{ padding: '6px 8px' }}>Non-thermal Bremsstrahlung</td>
                  <td style={{ padding: '6px 8px' }}>Neupert Index = Verified (dF_SXR/dt ∝ F_HXR)</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Section 2: AI Nowcast Probabilities */}
          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: '0.88rem', fontWeight: 800, color: '#F47216', borderBottom: '1px dashed rgba(244,114,22,0.4)', paddingBottom: 4, marginBottom: 10 }}>
              2. DEEP LEARNING PROBABILISTIC FORECAST (SOLARFLARENET)
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, textAlign: 'center' }}>
              <div style={{ background: 'rgba(255,255,255,0.02)', padding: 10, borderRadius: 6, border: '1px solid #1E293B' }}>
                <div style={{ fontSize: '0.72rem', color: '#94A3B8' }}>5-MIN PROBABILITY</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 900, color: '#F47216' }}>{p5}%</div>
              </div>
              <div style={{ background: 'rgba(255,255,255,0.02)', padding: 10, borderRadius: 6, border: '1px solid #1E293B' }}>
                <div style={{ fontSize: '0.72rem', color: '#94A3B8' }}>15-MIN PROBABILITY</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 900, color: '#FB923C' }}>{p15}%</div>
              </div>
              <div style={{ background: 'rgba(255,255,255,0.02)', padding: 10, borderRadius: 6, border: '1px solid #1E293B' }}>
                <div style={{ fontSize: '0.72rem', color: '#94A3B8' }}>30-MIN PROBABILITY</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 900, color: '#38BDF8' }}>{p30}%</div>
              </div>
              <div style={{ background: 'rgba(255,255,255,0.02)', padding: 10, borderRadius: 6, border: '1px solid #1E293B' }}>
                <div style={{ fontSize: '0.72rem', color: '#94A3B8' }}>24-HR OUTLOOK</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 900, color: '#A78BFA' }}>{p24}%</div>
              </div>
            </div>
          </div>

          {/* Section 3: Targeted Strategic Directives */}
          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: '0.88rem', fontWeight: 800, color: '#F47216', borderBottom: '1px dashed rgba(244,114,22,0.4)', paddingBottom: 4, marginBottom: 10 }}>
              3. TARGETED SOVEREIGN INFRASTRUCTURE DIRECTIVES
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <strong style={{ minWidth: 160, color: '#F59E0B' }}>CIVIL AVIATION (DGCA):</strong>
                <span style={{ color: '#E2E8F0' }}>
                  {rLevel}. Monitor 5–15 MHz HF propagation degradations over Indian airspace; prepare satellite voice relay on trans-oceanic flight routes.
                </span>
              </div>
              <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <strong style={{ minWidth: 160, color: '#EF4444' }}>ISRO SPACECRAFT (ISTRAC):</strong>
                <span style={{ color: '#E2E8F0' }}>
                  {sLevel}. Initiate periodic EDAC memory scrubbing on GSAT & LEO platforms. Safeguard sensitive star tracker optical assemblies.
                </span>
              </div>
              <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <strong style={{ minWidth: 160, color: '#38BDF8' }}>NAVIC NAVIGATION:</strong>
                <span style={{ color: '#E2E8F0' }}>
                  {gLevel}. Increased ionospheric delay scintillation over low-latitude master stations. Apply dual-frequency L5/S corrections.
                </span>
              </div>
              <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <strong style={{ minWidth: 160, color: '#10B981' }}>NATIONAL POWER GRID (PGCIL):</strong>
                <span style={{ color: '#E2E8F0' }}>
                  Geomagnetically Induced Current (GIC) risk within nominal limits. Keep reactive power reserves standing by on 765kV EHV lines.
                </span>
              </div>
            </div>
          </div>

          {/* Footer Validation Signature */}
          <div style={{
            borderTop: '1px solid #334155',
            paddingTop: 12,
            marginTop: 20,
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            fontSize: '0.72rem',
            color: '#64748B'
          }}>
            <div>
              ISSUED BY: <strong>ADITYA-L1 ASWOC OPERATIONAL CONSOLE</strong><br />
              VALIDATED WITH: <strong>ISRO PRADAN LEVEL-2 ARCHIVE</strong>
            </div>
            <div style={{ textAlign: 'right' }}>
              PRINCIPAL INVESTIGATOR: <strong>KRISH PATEL</strong><br />
              SYSTEM AUTHENTICATION: <strong>SHA256-{bulletinId.slice(-8)}-VERIFIED</strong>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
